language: ruby
cache:
  - apt
  - bundler

before_install:
  - sudo apt-get update
  - gem install bundler --no-document

install:  travis_wait bundle install --without guard --jobs 7 --retry=3
script: "bundle exec thor spec"
# prevent PR branches from running travis twice
branches:
  only:
    - master

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: ruby-head
    - rvm: 2.5
      env:
        CHEFSTYLE: 1
      script: bundle exec rake style
