sudo: true
language: ruby
cache: bundler

before_install:
  - sudo apt-get update
  - sudo apt-get install libgecode-dev
  - gem install bundler --no-ri --no-rdoc

script: "bundle exec thor spec"
env: USE_SYSTEM_GECODE=1
bundler_args: --without dev

# prevent PR branches from running travis twice
branches:
  only:
    - master

matrix:
  include:
    - rvm: 2.1.9
    - rvm: 2.2.5
    - rvm: 2.3.1
  allow_failures:
    - rvm: 2.3.1


